# Generated by Django 5.0.3 on 2024-12-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvedorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.IntegerField(choices=[(1, 'Padrao'), (2, 'Twilio')], default=1)),
                ('prioridade', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=False)),
                ('host', models.CharField(max_length=500)),
                ('port', models.CharField(max_length=10)),
                ('sender_name', models.CharField(max_length=250)),
                ('sender_email', models.CharField(max_length=250)),
                ('host_user', models.CharField(max_length=250)),
                ('host_password', models.CharField(max_length=250)),
                ('use_tls', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProvedorSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.IntegerField(choices=[(1, 'Padrao'), (2, 'Twilio')], default=1)),
                ('prioridade', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=False)),
                ('account_id', models.CharField(max_length=250)),
                ('auth_token', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
