# Generated by Django 5.0.3 on 2024-12-10 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detalheerro'),
        ('provedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusnotificacao',
            name='titulo',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.CreateModel(
            name='NotificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_vinculados', to='core.notificacao')),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_email', to='provedor.provedoremail')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_vinculados', to='core.notificacao')),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_sms', to='provedor.provedorsms')),
            ],
        ),
    ]
